### ISSUE TITLE
行数が多いとテキストエリアを突き抜ける

### ISSUE THREAD

**Issue by rmuraoka** [ow-hirata/smarter-testrail-editor#3]
suitesの画面にて

![スクリーンショット 2021-09-21 11 13 36](https://user-images.githubusercontent.com/39903184/134101629-00803159-b827-4f44-ade6-49292a6f0301.png)

**Comment by kzmshx** [comment]
@rmuraoka 
本件 v0.0.3 で修正済みですので、一度ご確認をお願いできますか？

**Comment by rmuraoka** [comment]
@kzmsh 
気付くのが遅くなりましたがこちら修正されていることが確認できました！ありがとうございます！
