### ISSUE TITLE
suite画面でsubsectionを編集しようとすると入力済みのdescriptionが反映されていない

### ISSUE THREAD

**Issue by rmuraoka** [ow-hirata/smarter-testrail-editor#5]
表題の通り
入力済みのsubsectionを編集すると発生
（拡張機能をOFFにした場合は発生しない）

**Comment by kzmshx** [comment]
@rmuraoka 
本件 v0.0.3 で修正済みですので、一度ご確認をお願いできますか？

**Comment by rmuraoka** [comment]
@kzmsh こちらも修正されているのが確認できました！ありがとうございます！
